[tool.poetry]
name = "ndviet-test-automation"
version = "0.1.0"
description = ""
authors = ["Viet Nguyen Duc <nguyenducviet4496@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
